it is broken.
MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.

what the ever loving fuck. work all weekend, and all I do is build new segments and it breaks. completely. fuck me.