massive error in saving to the SessionData File
I am not sure how this is crashing, and I am wondering if I will need to strip it and try another route.

IOException: Sharing violation on path C:\Users\User\Documents\GitHub\FeralCookies\LearningFER2 - StandardLight\Assets\SessionData

System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
System.IO.File.Create (System.String path, System.Int32 bufferSize) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.File.Create (System.String path) (at <695d1cc93cca45069c528c15c9fdd749>:0)
BayatGames.SaveGameFree.SaveGame.Save[T] (System.String identifier, T obj, System.Boolean encode, System.String password, BayatGames.SaveGameFree.Serializers.ISaveGameSerializer serializer, BayatGames.SaveGameFree.Encoders.ISaveGameEncoder encoder, System.Text.Encoding encoding, BayatGames.SaveGameFree.SaveGamePath path) (at Assets/BayatGames/SaveGameFree/Scripts/SaveGame.cs:354)
BayatGames.SaveGameFree.SaveGame.Save[T] (System.String identifier, T obj, BayatGames.SaveGameFree.Serializers.ISaveGameSerializer serializer) (at Assets/BayatGames/SaveGameFree/Scripts/SaveGame.cs:247)
SaveGamesFreeJsonSaveManagerImplementation.SaveDataAsync[T] (System.String key, T value, System.Threading.CancellationToken cancelToken) (at Assets/RhythmMounain/Scripts/Runtime/SaveGamesFreeJsonSaveManagerImplementation.cs:23)
SaveManager.SaveData[T] (System.String key, T value) (at Assets/RhythmMounain/Scripts/Runtime/SaveManager.cs:72)
ScoringSystem.RecordResults () (at Assets/RhythmMounain/Scripts/Runtime/ScoringSystem.cs:20)
GameManager.WinGame () (at Assets/RhythmMounain/Scripts/Runtime/GameManager.cs:97)
GameManager.Update () (at Assets/RhythmMounain/Scripts/Runtime/GameManager.cs:88)